### ISSUE TITLE
Maven build success - payara micro start fails - wrong character encoding boot.properties

### ISSUE THREAD

**Issue by dreasb** [payara/ecosystem-maven#47]
When I build a payara-micro service within maven, the build runs successfully. But the starting of the payara-mircobundle fails with IllegalArgumentException.

**Defect**
- mvn clean install runs successfully
- java -jar microbundle.jar fails

`java -jar target\token-microbundle.jar
Jun 25, 2018 12:53:31 PM fish.payara.micro.PayaraMicro main
SCHWERWIEGEND: null
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at fish.payara.micro.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:107)
        at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:70)
        at fish.payara.micro.boot.PayaraMicroLauncher.main(PayaraMicroLauncher.java:79)
        at fish.payara.micro.PayaraMicro.main(PayaraMicro.java:397)
Caused by: java.lang.IllegalArgumentException: Malformed \uxxxx encoding.`

**My system:**
- Microsoft Windows 10
- Payara Micro 5.182
- Maven 3.5.3
- Java 1.8.0_121

**Reason**
The generated payara-boot.properties file within the MICRO-INF subfolder contains the environment parameter java.library.path. Within this path - the PATH variable is included. But: If any path variable contains a folder with the character sequence "\u" like (c:\myprograms\portablegit\usr\bin). The execution / start of the payara-microbundle fails.

**Workaround**
Changing the path variable before build or set appendSystemProperties to false. In the second case the java.library.path will not set to the payara-boot.properties

**Comment by ruyakubu** [comment]
I run into the same issue when trying to run my Java MicroProfile application using Payara Micro on my local environment.

Windows 10 
Maven 3.5.4
Java 1.8.0_181

My environment variables “PATH” has some entries that contains “\u” (e.g. C:**\U**sers\myalias\...).  Apparently, Java is misinterpreting the substring in the generated payara-boot.properties file as a special unicode encoding.

\target\extracted-payaramicro\MICRO-INF\payara-boot.properties

Unfortunately, in order for a developer to run their Payara Micro application, they will need to remove all the entries PATHs that contain any "\U" substring.

This BUG is not a good developer experience.  A fix is needed.

Thanks.

**Comment by brunoborges** [comment]
Did a quick review in the maven plugin code, and the bug may be located here:
https://github.com/payara/ecosystem-maven/blob/master/payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/processor/SystemPropAppendProcessor.java#L87-L94
 
It may be the case where String is not being properly converted/escaped to avoid Unicode (\u) conversion.

**Comment by jGauravGupta** [comment]
Hi @ruyakubu ,

Can you share the sample artifact(jar) to reproduce the issue.

**Comment by brunoborges** [comment]
Hi @jGauravGupta,

The sample @ruyakubu is trying to run is this one: 

http://github.com/azure-samples/microprofile-hello-azure

**Comment by jGauravGupta** [comment]
Thanks @brunoborges :)

**Comment by jGauravGupta** [comment]
Fixed by #55

**Comment by ewoudwerkman** [comment]
I still have this issue when trying to run the demo from https://start.microprofile.io/ using Payara.

**Comment by jGauravGupta** [comment]
Generated app from https://start.microprofile.io/  but can't reproduce the issue anymore, @ewoudwerkman can you help us by providing more details.

**Comment by McFoggy** [comment]
@jGauravGupta it is still failing for me, context is:

- Windows10 version 1709
- maven 3.6.1
- jvm 8 or 11 (oracle 1.8.0_162 or 11+28)
- app created with https://start.microprofile.io/ MP 2.1 all options selected

**Comment by aglynn42** [comment]
Still have this issue (yes, I know not using Windows would be a solution, but I don't have any choice in the matter).  Where do I escape the system properties in Java 8/Windows 10.

**Comment by jGauravGupta** [comment]
Hi @aglynn42,

Can you share the list of system property `System.getProperties()` to reproduce it?
